services:
  # Test runner
  test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "git config --global --add safe.directory /app && exec \"$@\"", "--"]