name: Jekyll site CI

on:
  push:
    branches: [ "main", "jekyll-1" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Create Jekyll config
      run: |
        cat > _config.yml << 'EOF'
        title: "The GitScrolls"
        description: "Nine Sacred Teachings for Modern Developers"
        baseurl: "/gitscrolls"
        url: "https://gitscrolls.github.io"
        markdown: kramdown
        highlighter: rouge
        theme: minima
        EOF
    
    - name: Add/Replace frontmatter for GitScrolls
      run: |
        # Process each .md file to ensure consistent frontmatter
        for file in *.md; do
          if [[ -f "$file" ]]; then
            # Extract title from first heading
            title=$(head -20 "$file" | grep "^# " | head -1 | sed 's/^# //' | sed 's/GitScroll [IVX]*: //')
            if [[ -z "$title" ]]; then
              title=$(basename "$file" .md)
            fi
            
            # Extract content (skip frontmatter if it exists)
            if grep -q "^---" "$file"; then
              # Skip frontmatter block (from first --- to second ---)
              content=$(awk '/^---$/{if(++count==2) flag=1; next} flag' "$file")
            else
              # No frontmatter, use entire file
              content=$(cat "$file")
            fi
            
            # Create new file with standardized frontmatter using printf (no heredoc!)
            printf '%s\n' '---' 'layout: post' "title: \"$title\"" 'date: 2025-05-30' '---' '' > "${file}.new"
            echo "$content" >> "${file}.new"
            mv "${file}.new" "$file"
          fi
        done
    
    - name: Create index page
      run: |
        cat > index.md << 'EOF'
        ---
        layout: home
        title: "The GitScrolls"
        ---
        
        # The Nine GitScrolls
        
        Sacred teachings for modern developers who seek wisdom in version control and beyond.
        
        {% for post in site.posts reversed %}
        - [{{ post.title }}]({{ post.url }})
        {% endfor %}
        EOF
    
    - name: Build the site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
